var fs = require('fs')
//var _ = require('lodash')
var cxjs = require('./index.js')
var content = fs.readFileSync('small_graph.cx')
var rawCX = JSON.parse(content)
var utils = new cxjs.cyNetworkUtils()
var niceCX = utils.rawCXtoNiceCX(rawCX)
console.log(niceCX)
var cx2Js = new cxjs.cxToJs(utils)
var elements = cx2Js.cyElementsFromNiceCX(niceCX, {})
console.log('Elements:')
console.log(JSON.stringify(elements))
var style = cx2Js.cyStyleFromNiceCX(niceCX, {})
console.log('Style:')
console.log(JSON.stringify(style))
var cxBGColor = cx2Js.cyBackgroundColorFromNiceCX(niceCX)