var fs = require("fs")
var _ = require("lodash")
var cxjs = require('./index.js')
var content = fs.readFileSync("small_graph.cx")
var rawCX = JSON.parse(content)
var utils = new cxjs.cyNetworkUtils()
var niceCX = utils.rawCXtoNiceCX(rawCX)
console.log(niceCX)
var x = new cxjs.cxToJs(utils)
var y = x.cyElementsFromNiceCX(niceCX, {})
console.log("Elements:")
console.log(y)